In [23]:
# Importing libraries
import pandas as pd
def recommendation():
    
    # Read csv file into a pandas dataframe
    df = pd.read_csv("books.csv")
    df = df[df.language_code =='eng']
    df['Title'] = df['title'].str.split('(').str[0]
    print("Enter rating w/wo <rating> or random for book suggestion")
    search= input("enter to search ")
    if search=="random":
        df_new= df.sample(replace=True)[['Title', 'authors',"rating"]]
        print("Title: ", df_new[['Title']].to_string(index=False, header=False))
        print("Author: ", df_new[['authors']].to_string(index=False, header=False))
        print("Rating: ", df_new[['rating']].to_string(index=False, header=False))
        return "Enjoy!"
    elif "rating" in search:
            search=search.split()
            rate=float(search[1])
            df_rate = df[df['rating'].astype(float) >= rate]
            df_new= df_rate.sample(replace=True)[['Title', 'authors',"rating"]]
            print("Title: ", df_new[['Title']].to_string(index=False, header=False))
            print("Author: ", df_new[['authors']].to_string(index=False, header=False))
            print("Rating: ", df_new[['rating']].to_string(index=False, header=False))
            return "Enjoy!"
print(recommendation())

Enter rating w/wo <rating> or random for book suggestion
Title:  The Parrot's Lament  and Other True Tales of Animal Intrigue  Intelligence  and Ingenuity
Author:  Eugene Linden
Rating:  3.93
Enjoy!

In [24]:
def author_search():
    # Read csv file into a pandas dataframe
    df = pd.read_csv("books.csv")
    df = df[df.language_code =='eng']

    #reading and cleaning author's name
    auth_inp = input("Enter the author's name: ")
    clean_auth_inp=auth_inp.lstrip().rstrip().title()
    
    #showing title, rating and author for selected name
    author_df = df[df.authors.str.find(clean_auth_inp)>=0][['title','authors','rating']]
    print(author_df)
    return None
author_search()

                                                   title  \
0      Harry Potter and the Half-Blood Prince (Harry ...
1      Harry Potter and the Order of the Phoenix (Har...
2      Harry Potter and the Chamber of Secrets (Harry...
3      Harry Potter and the Prisoner of Azkaban (Harr...
4      Harry Potter Boxed Set  Books 1-5 (Harry Potte...
6           Harry Potter Collection (Harry Potter  #1-6)
613    Harry Potter Schoolbooks Box Set: Two Classic ...
615    Harry Potter and the Half-Blood Prince (Harry ...
1233   Harry Potter and the Prisoner of Azkaban (Harr...
4416   Harry Potter and the Chamber of Secrets (Harry...
8876   Harry Potter and the Sorcerer's Stone (Harry P...
9451   The Weimar Republic: The Crisis of Classical M...
10344  Fantastic Beasts and Where to Find Them (Hogwa...
10679  Harry Potter and the Goblet of Fire (Harry Pot...

                                   authors rating
0               J.K. Rowling/Mary GrandPré   4.57
1               J.K. Rowling/Mary GrandPré   4.49
2                             J.K. Rowling   4.42
3               J.K. Rowling/Mary GrandPré   4.56
4               J.K. Rowling/Mary GrandPré   4.78
6                             J.K. Rowling   4.73
613                           J.K. Rowling    4.4
615                           J.K. Rowling   4.57
1233                          J.K. Rowling   4.56
4416            J.K. Rowling/Mary GrandPré   4.42
8876            J.K. Rowling/Mary GrandPré   4.47
9451   Detlev J.K. Peukert/Richard Deveson   3.84
10344          Newt Scamander/J.K. Rowling   3.99
10679                         J.K. Rowling   4.56

In [25]:
def sortbylanguage(language):
    df = pd.read_csv("books.csv")
    df=df.loc[df['language_code']==language].sort_values('rating', ascending=False).head(20)
    return df

In [26]:
lang=input("Enter the language code")
new_df=sortbylanguage(lang)
new_df

,bookID,title,authors,rating,language_code,num_pages,ratings_count,text_reviews_count,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
4412,15872,Harry Potter y el misterio del príncipe (Harry...,J.K. Rowling/Gemma Rovira Ortega,4.57,spa,602,5104,386,NaN,NaN,NaN,NaN
4413,15876,Harry Potter y la Orden del Fénix (Harry Potte...,J.K. Rowling,4.49,spa,893,5637,458,NaN,NaN,NaN,NaN
4969,17950,Obra Poética,Jorge Luis Borges,4.49,spa,645,50,3,NaN,NaN,NaN,NaN
988,3357,Harry Potter Y La Piedra Filosofal (Harry Pott...,J.K. Rowling,4.47,spa,254,142,12,NaN,NaN,NaN,NaN
4605,16569,Ficciones,Jorge Luis Borges/Gordon Botherston/Peter Hulme,4.45,spa,232,90,4,NaN,NaN,NaN,NaN
3710,13449,La Milla Verde,Stephen King/María Eugenia Ciocchini Suárez,4.44,spa,448,9,1,NaN,NaN,NaN,NaN
9067,35313,La Ley del Exito,Paramahansa Yogananda,4.44,spa,32,0,0,NaN,NaN,NaN,NaN
7872,30270,Pacto Con un Demonio,Kim Harrison,4.39,spa,512,0,0,NaN,NaN,NaN,NaN
1659,5794,El Aleph,Jorge Luis Borges,4.38,spa,253,146,9,NaN,NaN,NaN,NaN
8882,34327,La Biblia de los Critales: Guia definitiva de ...,Judy Hall,4.38,spa,383,6,0,NaN,NaN,NaN,NaN
6771,25395,Una Vida Con Proposito Volumen 6,Rick Warren,4.35,spa,56,26,3,NaN,NaN,NaN,NaN
3165,11613,La danza de la muerte,Stephen King/Eduardo Goligorsky,4.34,spa,613,64,3,NaN,NaN,NaN,NaN
7355,28344,Los hermanos Karamazov,Fyodor Dostoyevsky/Alexander Pushkin/Guillermo...,4.32,spa,805,30,4,NaN,NaN,NaN,NaN
8255,31761,El Dia Que Nietzsche Lloró,Irvin D. Yalom,4.32,spa,445,66,4,NaN,NaN,NaN,NaN
7518,28860,El Evangelio Según Jesucristo,José Saramago/Basilio Losada,4.29,spa,480,34,6,NaN,NaN,NaN,NaN
9688,38665,Pedro Páramo / El Llano en llamas,Juan Rulfo,4.29,spa,290,5103,118,NaN,NaN,NaN,NaN
9690,38669,Pedro Paramo / El Llano En Llamas,Juan Rulfo,4.29,spa,290,6,2,NaN,NaN,NaN,NaN
9959,40130,Leonardo da Vinci: Obra pictorica completa y o...,Frank Zöllner/Johannes Nathan/Frank Zöllner,4.26,spa,696,56,4,NaN,NaN,NaN,NaN
11114,45607,Las Crónicas de Narnia,C.S. Lewis/Margarita E. Valdes/Gemma Gallart/P...,4.26,spa,816,186,11,NaN,NaN,NaN,NaN
5822,21803,La princesa prometida,William Goldman,4.26,spa,480,39,7,NaN,NaN,NaN,NaN

In [27]:
def bookName(name):
    df = pd.read_csv("books.csv")
    df=df.loc[df['title']==name].sort_values('rating', ascending=False).head(20)
    return df

In [28]:
nam=input("Enter the title of the book")
new_df=bookName(nam)
new_df

,bookID,title,authors,rating,language_code,num_pages,ratings_count,text_reviews_count,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
39,67,The Known World,Edward P. Jones,3.83,eng,388,29686,2626,NaN,NaN,NaN,NaN
40,68,The Known World,Edward P. Jones/Kevin R. Free,3.83,en-US,14,55,12,NaN,NaN,NaN,NaN
41,69,The Known World,Edward P. Jones,3.83,eng,576,22,3,NaN,NaN,NaN,NaN
3193,11684,The Known World,Edward P. Jones,3.83,eng,388,449,83,NaN,NaN,NaN,NaN